### ISSUE TITLE
Page has been temporarily disabled due to a misconfigured custom domain.

### ISSUE THREAD

**Issue by tillarnold** [Gozala/try-wisp#7]
When visiting http://jeditoolkit.com/wisp/ (or http://jeditoolkit.com/try-wisp) an error message is shown: 

> This page has been temporarily disabled due to a misconfigured custom domain.

I think that this is caused by the [GitHub Pages legacy IP brownout](https://github.com/blog/1925-github-pages-legacy-ip-brownout).

**Comment by tillarnold** [comment]
The site is working again. Was this an issue on my end?

**Comment by Gozala** [comment]
> The site is working again. Was this an issue on my end?

No I actually had to update DNS settings. Changes have not being reflected for me yet, I guess server I'm hitting has not updated DNS records yet.
